spring:
  datasource:
    url: jdbc:h2:mem:booksdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true  # to allow DB initialization scripts (since Spring Boot version 2.5.0)
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl:
        auto: update
  h2:
    console:
      enabled: true

  jackson:
    default-property-inclusion: non_null

server:
   port: 9090

auth:
  secret: secret